# Generated by Django 5.0.4 on 2024-05-19 19:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('image', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Canzone',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('album', models.ManyToManyField(to='playlistener.album')),
                ('artista', models.ManyToManyField(to='playlistener.artista')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine', models.IntegerField()),
                ('canzone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlistener.canzone')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(default='Nuova Playlist', max_length=100)),
                ('tag', models.CharField(choices=[('fr', ''), ('sp', 'sport'), ('vg', 'viaggio')], default='fr', max_length=2)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='')),
                ('desc', models.TextField(blank=True, max_length=300, null=True)),
                ('canzone', models.ManyToManyField(through='playlistener.Ordine', to='playlistener.canzone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='ordine',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlistener.playlist'),
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfp', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
