# Generated by Django 5.0.4 on 2024-04-26 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlistener', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utente',
        ),
    ]
