# Generated by Django 5.0.4 on 2024-05-20 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlistener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordine',
            old_name='ordine',
            new_name='n',
        ),
    ]
