# Generated by Django 5.0.4 on 2024-05-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlistener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='tag',
            field=models.CharField(choices=[('fr', 'libero'), ('sp', 'sport'), ('vg', 'viaggio')], default='fr', max_length=2),
        ),
    ]
