# Generated by Django 5.0.4 on 2024-05-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlistener', '0002_alter_playlist_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='tag',
            field=models.CharField(choices=[('libero', 'libero'), ('sport', 'sport'), ('viaggio', 'viaggio')], default='libero', max_length=14),
        ),
    ]
