# Generated by Django 5.0.4 on 2024-05-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlistener', '0003_alter_playlist_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='durata_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='energia_min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
