# Generated by Django 5.0.4 on 2024-04-24 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlistener', '0003_playlist_utente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='utente',
        ),
    ]
