# Generated by Django 5.0.4 on 2024-04-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlistener', '0003_utente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='nome',
            field=models.CharField(default='Nuova Playlist', max_length=100),
        ),
    ]
