# Generated by Django 5.0.4 on 2024-05-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlistener', '0004_playlist_durata_min_playlist_energia_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='energia_min',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
