# Generated by Django 5.0.4 on 2024-04-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlistener', '0004_alter_playlist_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='tag',
            field=models.CharField(choices=[('fr', ''), ('sp', 'sport'), ('vg', 'viaggio')], default='fr', max_length=2),
        ),
    ]
