# Generated by Django 5.0.4 on 2024-05-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlistener', '0006_alter_playlist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
