# Generated by Django 5.0.4 on 2024-05-19 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlistener', '0007_album_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine', models.IntegerField()),
                ('Playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlistener.playlist')),
                ('canzone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlistener.canzone')),
            ],
        ),
        migrations.AlterField(
            model_name='playlist',
            name='canzone',
            field=models.ManyToManyField(through='playlistener.Ordine', to='playlistener.canzone'),
        ),
    ]
